server:
  port: 8080

spring:
  application:
    name: mcp-client-demo
  ai:
    retry:
      max-attempts: 3
      backoff:
        delay: 1000
        multiplier: 2
    anthropic:
      api-key: ${ANTHROPIC_API_KEY:demo-key-replace-with-actual}
      model: claude-3-7-sonnet-20250219
      options:
        temperature: 0.7
        max-tokens: 4000
    mcp:
      client:
        enabled: true
        name: mcp-client-demo
        version: 1.0.0
        type: SYNC
        request-timeout: 30s
        #sse:
        #  connections:
        #    local-server:
        #      url: http://localhost:8092/api
      # Disable embedded server since we're using the standalone mcp-server-demo
      server:
        enabled: false
  thymeleaf:
    cache: false
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

# Logging Configuration
logging:
  level:
    org.springframework.ai: DEBUG
    com.example: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    io.modelcontextprotocol: TRACE

# Duffel API configuration
duffel:
  api-key: ${DUFFEL_API_KEY:replace-with-your-api-key}
  base-url: https://api.duffel.com/air
  card-base-url: https://api.duffel.cards
  links-base-url: https://api.duffel.com/links
  version: v2
  auth-token: ${DUFFEL_API_KEY:replace-with-your-api-key}

app:
  tools:
    autoResolve: true  # Set to false to disable automatic tool resolution